// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVSh35zYeOT9t0sU4BwxPxkt34aqVgEvQ',
    appId: '1:535825486071:web:2c586836127aa2468a43f2',
    messagingSenderId: '535825486071',
    projectId: 'flutter-firebase-5092a',
    authDomain: 'flutter-firebase-5092a.firebaseapp.com',
    storageBucket: 'flutter-firebase-5092a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC75DgL86HyQ0tlli7wO7ef49H9_vZ5-Xg',
    appId: '1:535825486071:android:25189c8b8d3ad8978a43f2',
    messagingSenderId: '535825486071',
    projectId: 'flutter-firebase-5092a',
    storageBucket: 'flutter-firebase-5092a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUkD0JJU-gbExoGEg3abSd8z38eE8xzLY',
    appId: '1:535825486071:ios:a5f4d43dc879aae48a43f2',
    messagingSenderId: '535825486071',
    projectId: 'flutter-firebase-5092a',
    storageBucket: 'flutter-firebase-5092a.appspot.com',
    iosClientId:
        '535825486071-8reusu78qch1k1qmj2dlfo6c3okmajk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUkD0JJU-gbExoGEg3abSd8z38eE8xzLY',
    appId: '1:535825486071:ios:a5f4d43dc879aae48a43f2',
    messagingSenderId: '535825486071',
    projectId: 'flutter-firebase-5092a',
    storageBucket: 'flutter-firebase-5092a.appspot.com',
    iosClientId:
        '535825486071-8reusu78qch1k1qmj2dlfo6c3okmajk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
